format = """
[](#EA0599)\
$os\
$username\
[](bg:#9A0F98 fg:#EA0599)\
$git_branch\
$git_status\
[](fg:#9A0F98 bg:#6A0572)\
$golang\
$java\
$nodejs\
$python\
$rust\
$zig\
[](fg:#6A0572 bg:#39065A)\
$time\
[](fg:#39065A)\
$line_break\
$directory\
$shell\
$character \
"""

add_newline = true

scan_timeout = 5000

#format = """
# $username \
# ($java$python$golang$nodejs) \
# $git_status$git_branch\
# $time
# $directory $character  
#"""

[shell]
powershell_indicator = '\(pwsh\)'
zsh_indicator = ""
style = '(bold fg:#39065A)'
disabled = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#EA0599"
style_root = "bg:#EA0599"
format = '[[]($style) karolina ]($style)'
disabled = false

[directory]
style = "fg:#40E0D0"
format = "[ $path ]($style)"
truncation_length = 25
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"source" = "</>"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[git_branch]
symbol = ""
style = "bg:#9A0F98"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#9A0F98"
disabled = false
format = '([\[$all_status$ahead_behind\]]($style))'
stashed = 'stashed ${count}'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "conflict ${count}(fg:#ff0000)"
deleted = "✘${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"

[golang]
symbol = " "
style = "bg:#6A0572"
format = '[ $symbol Go ($version) ]($style)'

[java]
symbol = " "
style = "bg:#6A0572"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#6A0572"
format = "[ $symbol Node.js ($version) ]($style)"
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[python]
symbol = " "
style = "bg:#6A0572"
format = "[ $symbol Python ($version) ($virtualenv)]($style)"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python"]
detect_extensions = []
version_format = "v${raw}"

[zig]
symbol = "↯ "
style = "bg:#6A0572"
format = '[ $symbol Zig ($version )]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "bg:#6A0572"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#39065A"
format = '[ ♥ $time ]($style)'

[status]
disabled = false
format = "[ $signal_name $symbol ]($style)"
map_symbol = true
sigint_symbol = "[✘](fg:#d60202 bg:#444444)"
style = "bg:#444444"
success_symbol = "[✔](fg:green bg:#444444)"
symbol = "[✘](fg:#d60202 bg:#444444)"

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "fg:#9b9b9b bg:#444444"
format = "[ $duration ]($style)"

[custom]
[custom.direnv]
format = "[](fg:#7a7a7a bg:#444444)[ $symbol ]($style)"
style = "fg:#7a7a7a bg:#444444"
symbol = "[▼](fg:white bg:#444444)"
when = "test \"$DIRENV_WATCHES\" != \"\""

[line_break]
disabled = false

[character]
format = "$symbol"
success_symbol = "[»](bold fg:#32CD32)"
error_symbol = "[¬](bold red)"
disabled = false
